application: haabaablog
version: 1
runtime: python
api_version: 1

handlers:
#- url: .*
#  script: main.py
- url: /
  script: main.py
- url: /chat
  script: main.py
- url: /swf
  static_dir: swf
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

